import { expect, test } from '@playwright/test'
import fs from 'node:fs/promises'

test.beforeEach(async ({ page }) => {
  await page.route('**/api/catalog-variant?*', (route) => route.fulfill({ json: { ok: false } }))
})

test('keyboard preview uses manual activation and exposes product selection', async ({ page }) => {
  const scripts: string[] = []
  page.on('request', (request) => { if (request.resourceType() === 'script') scripts.push(request.url()) })
  await page.goto('/')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Skip to customization' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('complementary', { name: 'Customize your build' })).toBeFocused()
  const photo = page.getByRole('tab', { name: 'Photographed product' })
  const three = page.getByRole('tab', { name: 'Interactive 3D' })
  await photo.focus()
  await photo.press('ArrowRight')
  await expect(three).toBeFocused()
  await expect(photo).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('canvas')).toHaveCount(0)
  expect(scripts.some((url) => url.includes('WeldingHoodViewer'))).toBe(false)
  await three.press('Home')
  await expect(photo).toBeFocused()
  await photo.press('End')
  await expect(three).toBeFocused()
  await three.press('Enter')
  await expect(three).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tabpanel', { name: 'Interactive 3D' })).toBeVisible()
  await expect(page.locator('canvas')).toBeVisible()
  await three.press('ArrowLeft')
  await photo.press('Space')
  await expect(page.locator('canvas')).toHaveCount(0)
  await expect(photo).toHaveAttribute('tabindex', '0')
  await expect(three).toHaveAttribute('tabindex', '-1')
  const harness = page.getByRole('navigation', { name: 'Customizable products' }).getByRole('button', { name: /Radio Harness/i })
  await harness.click()
  await expect(harness).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('group', { name: /1. Starting build/ })).toBeVisible()
  await page.getByRole('button', { name: 'Western floral', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Tooling notes' })).toBeVisible()
})

test('lazy order tools remain keyboard reachable without intersection observation', async ({ page }) => {
  await page.addInitScript(() => {
    window.IntersectionObserver = class {
      observe() {} unobserve() {} disconnect() {} takeRecords() { return [] }
      root = null; rootMargin = ''; thresholds = []
    } as unknown as typeof IntersectionObserver
  })
  await page.goto('/')
  const open = page.getByRole('button', { name: 'Open order request' })
  await open.focus()
  await open.press('Enter')
  await expect(page.getByRole('region', { name: 'Custom order request', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('textbox', { name: /Name/ })).toBeFocused()
})

test('order validation and prepared packet manage focus without reload focus theft', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('region', { name: 'Custom order request', exact: true }).scrollIntoViewIfNeeded()
  await page.getByRole('button', { name: 'Create Order Request', exact: true }).click()
  const name = page.getByRole('textbox', { name: /Name/ })
  await expect(name).toBeFocused()
  await expect(name).toHaveAttribute('aria-invalid', 'true')
  await expect(name).toHaveAccessibleDescription('Name is required.')
  await name.fill('Keyboard customer')
  await page.getByRole('button', { name: 'Create Order Request', exact: true }).click()
  const email = page.getByRole('textbox', { name: /Email/ })
  await expect(email).toBeFocused()
  await expect(email).toHaveAccessibleDescription('Enter an email address or phone number.')
  await email.fill('invalid')
  await expect(email).toHaveAccessibleDescription('Enter a valid email address.')
  await email.fill('keyboard@example.com')
  await expect(email).toHaveAttribute('aria-invalid', 'false')
  await page.getByRole('button', { name: 'Create Order Request', exact: true }).click()
  const ready = page.getByRole('region', { name: 'Prepared order request', exact: true })
  await expect(ready).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('checkbox', { name: /I understand/ })).toBeFocused()
  await fs.mkdir('playwright-output/screenshots', { recursive: true })
  await page.screenshot({ path: `playwright-output/screenshots/v027-order-${testInfo.project.name}.png` })
  await page.reload()
  await page.getByRole('button', { name: 'Restore saved request' }).click()
  await expect(ready).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('reduced motion and visible form focus preserve desktop and mobile layout', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const field = page.getByLabel('Leather finish preference')
  await field.focus()
  expect(await field.evaluate((node) => getComputedStyle(node).outlineStyle)).toBe('solid')
  const duration = await page.locator('.reference-choice').first().evaluate((node) => getComputedStyle(node).transitionDuration)
  expect(parseFloat(duration)).toBeLessThanOrEqual(0.001)
  await page.getByLabel('Construction notes').focus()
  expect(await page.getByLabel('Construction notes').evaluate((node) => getComputedStyle(node).outlineStyle)).toBe('solid')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await fs.mkdir('playwright-output/screenshots', { recursive: true })
  await page.screenshot({ path: `playwright-output/screenshots/v027-customization-${testInfo.project.name}.png` })
})
